#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the Hokuyo UTM 30LX usb connection."
echo ""

sudo cp `rospack find kitt3_drive`/90-hokuyo.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo /etc/init.d/udev restart

