#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the rplidar usb connection."
echo ""

sudo cp `rospack find kitt3_drive`/78-rplidar.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo /etc/init.d/udev restart

